vault_datadog_api_key: "83bfb7327d8367f7cd3dfcf813638ce9"

vault_some_db_postgres: "rc1a-d6nej4p76fe9decu.mdb.yandexcloud.net"
vault_some_db_database: "db"
vault_some_db_username: "sergey"
vault_some_db_password: "mypassword1234"
vault_some_db_port: "6432"