init:
	terraform init -backend-config=secret.backend.tfvars

upgrade:
	terraform init -upgrade -backend-config=secret.backend.tfvars

migrate:
	terraform init -migrate-state -backend-config=secret.backend.tfvars

plan:
	terraform plan

apply:
	terraform apply

destroy:
	terraform destroy

show:
	terraform show

graph:
	terraform graph
