[webservers]
server-1 ansible_host=62.84.113.34 ansible_user=sergey ansible_ssh_private_key_file=/home/sergey/.ssh/ssh-key-1765398419566.pub
server-2 ansible_host=178.154.227.121 ansible_user=sergey ansible_ssh_private_key_file=/home/sergey/.ssh/ssh-key-1765398419566.pub